package com.blogspot.qbeukes.cubes.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: quintin
 * Date: 14 Nov 2010
 * Time: 9:15:02 PM
 */
public class StatField {
  private JTextField statText;
  private JPanel statField;

  private String stat;

  public void setStat(long stat) {
    setStat(Long.toString(stat));
  }

  public void setStat(String stat) {
    this.stat = stat;

    if (SwingUtilities.isEventDispatchThread()) {
      displayStat();
    } else {
      SwingUtilities.invokeLater(new Runnable() {
        public void run() {
          displayStat();
        }
      });
    }
  }

  private void displayStat() {
    statText.setText(stat);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    statField = new JPanel();
    statField.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    statText = new JTextField();
    statText.setEditable(false);
    statField.add(statText, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return statField;
  }
}
