package com.blogspot.qbeukes.cubes.ui;

import com.blogspot.qbeukes.cubes.util.TimeUtil;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: quintin
 * Date: 14 Nov 2010
 * Time: 12:47:05 PM
 */
public class TimeField {
  private JPanel timeFieldPanel;
  private JTextField timeText;
  private JLabel timeLabel;

  private long milliseconds;

  public void setTime(long milliseconds) {
    this.milliseconds = milliseconds;

    if (SwingUtilities.isEventDispatchThread()) {
      displayTime();
    } else {
      SwingUtilities.invokeLater(new Runnable() {
        public void run() {
          displayTime();
        }
      });
    }
  }

  private void displayTime() {
    String time = TimeUtil.formatTime(milliseconds);
    timeText.setText(time);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    timeFieldPanel = new JPanel();
    timeFieldPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    timeText = new JTextField();
    timeText.setEditable(false);
    timeText.setText("");
    timeFieldPanel.add(timeText, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return timeFieldPanel;
  }
}
